### PR TITLE
[FIX] mrp_bom_component_change: Fixed product_template updating when …

### PR DESCRIPTION
**Pull request by Daniel-CA**
…product variants is installed

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Include a comment indicating why you add `product_tmpl_id`

**Comment by Daniel-CA** [comment]
Added info comment in code.

**Review by agaldona — APPROVED** [review]
:+1:

**Comment by Daniel-CA** [comment]
Can we merge this one?

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
