### PR TITLE
Merge update

### PR DESCRIPTION
**Pull request by davidtranhp**
Just want to merge Vietnamese translation files

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why don't you translate it on Transifex?

**Comment by davidtranhp** [comment]
I have done it within IDE because that way is easier and faster for me. In addition, I can run Odoo during translation to see if the translated terms I made is meaningful enough.
I am sorry if this would bother you.

**Comment by pedrobaeza** [comment]
No, no problem, while you make a proper PR without adding a bunch of file. quality_control and quality_control_stock are not anymore in this repo, but on OCA/manufacture, and you're adding them (among other files).

**Comment by davidtranhp** [comment]
That was my mistake. Could you please help exclude those quality_control and quality_control_stock? I just want to get Vietnamese translation files to be merged.

**Comment by pedrobaeza** [comment]
Sorry, I can't do it. You should do it on your side.

**Pull request closed without merging**
