### PR TITLE
[IMP] mrp_operations_extension: Added ondelete attribute on field routing_workcenter.

### PR DESCRIPTION
**Pull request by zamberjo**
Added ondelete attribute on field `routing_workcenter` on model
**mrp.operation.workcenter** to propagate delete to children routes.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put "cascade" on lower letters, but this seems good for me.

**Comment by oihane** [comment]
It should to go against https://github.com/OCA/manufacture/tree/8.0/mrp_operations_extension, shouldn't it?

**Comment by zamberjo** [comment]
Ok, I will replicate there.

So, this module is deprecated on odoomrp_wip? Are you going to remove it?

**Comment by oihane** [comment]
Removed from this repo `mrp_operations_extension` I close this PR.

**Pull request closed without merging**
