### PR TITLE
[IMP] mrp_operations_extension: Fine tuning of UI + computations

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Guided selection of operation inside routing lines for avoiding confusions.
- Homogenization of work centers selection in routing lines. You always add
  a workcenter line.
- Limit selectable workcenters on the work order according routing line.
- Views cleaning.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@anajuaristi, puedes ir probando estos cambios.

**Comment by anajuaristi** [comment]
Hi @pedrobaeza 

Tested in http://3119739-1061-1205f9.runbot2.odoo-community.org/web?db=3119739-1061-1205f9-all

Steps:
Create a new BOM for new product Granel including 2 materials and activate it
Assing a new routing "Mezcla" having 2 workcenters (Tolva1, Tolva2) with different cost values
Create a new manufacturing order for "granel"
Go to planned materials page and  push "compute data" 

I obtain the error:  ValueError Expected singleton: mrp.bom()

So I can not go fordward on testing to analyze the cost lines using different workcerters for same routing.

**Comment by pedrobaeza** [comment]
This is not working with variants yet. I have uninstalled the involved modules. Try again.

**Comment by anajuaristi** [comment]
About costs:

It's working fine. Tested the following use cases:
1. Set an specific bom for granel
2. Launch an MO
3. Compute date --> Creates the planned material and WO
4. Compute cost --> Machine cost is taken from routing line. (Here... I realized that onchange on cost product is taking the template value, it should take the product value)
5. Go to work orders page, open the workorder and change the machine
6. Compute cost --> Cost are recalculated and the price is taken from new machine --> :+1: 

---

Cycle calculation tests:
1. Set cycle capacity 200 on first machine and 2.5 hours/cycle
2. Set cycle capacity 500 on second machine and 3hours/cycle
3. Launch a manufacturing order for 200 units on first machine --> WO is taking correctly number of cycles = 1, time 2.5
4. Change MO and launch for 400 units on first machine --> WO is taking correctly number of cycles=2 , time 5
5. Change WO machine --> Quantity on MO is changed --> compute data --> WO is taking correctly number of cycles =1, time 3

So... I see NO ERROR on this part of calculations.

The only confusing thing is the label "Number of Cycles" on routing line. It's showing capacity per cycle, so it should be renamed to "capacity per cicle"
On example "capacity per cicle" on machine is 500, so "number of cycles" is 1, but it's showing "number of cycles"=500 on routing line and it's not true. 

---

Making more tests, I think singleton error was caused because "granel" had before 0 variants. Not sure about this 

Now...  
Even installing the variants modules, if BOM has an specific product set, it works properly. It only doesn't work when bom has not product_id but only template_id.

Tested wih a new product Granel2 having 2 different variants. When you launch an MO using granel2 as template, it's no showing an error, but "compute data" on MO is making nothing. It's not creating planned materials, no WOs
Let me know

**Comment by JMODaERP** [comment]
What module we have to uninstall for the test?.

**Comment by pedrobaeza** [comment]
All clean and checked. Merging.

**Pull request merged**
