### PR TITLE
[FIX] mrp_packaging_quant_manual_assign: 

### PR DESCRIPTION
**Pull request by agaldona**
Daba error al asignar quants de una of de packaging por cambios en modulo stock_quant_manual_assign

### CODE REVIEW

**Comment by agaldona** [comment]
Review please. @oihane @Daniel-CA @mikelarre @esthermm

**Comment by oihane** [comment]
It looks good to me :+1:

**Comment by esthermm** [comment]
:+1:

**Comment by Daniel-CA** [comment]
:+1:

**Pull request merged**
