### PR TITLE
[IMP] mrp_product_variants: load custom value in of configurator

### LINKED ISSUE #1163: [8.0][sale_product_variant_type] procurement does not accept range custom value
Place a sales order with a manufacture/mto product which has attribute type range and enter a custom value. Example: Attribute 'length', min=10.0, max=50.0
Running the procurement yields below error eventhough the custom value has been entered within the range in the sale order line.

ValidateError
Error while validating constraint
Custom value for attribute 'length' must be between 10.0 and 50.0. 

Tested on 
http://demo.odoomrp.com
db=September_2015_EN

### PR DESCRIPTION
**Pull request by agaldona**
Fixes #1163

### CODE REVIEW

**Comment by agaldona** [comment]
@odoomrp/developers review please

**Comment by esthermm** [comment]
:+1:

**Comment by Daniel-CA** [comment]
:+1:

**Comment by oihane** [comment]
@pedrobaeza anything to add?

**Comment by pedrobaeza** [comment]
No, I don't use this, but you should check coverage.

**Review by anajuaristi — APPROVED** [review]

**Pull request merged**
