### PR TITLE
[NEW mrp_final_product_lot]

### PR DESCRIPTION
**Pull request by alfredoavanzosc**
Nuevo módulo para cubrir los requerimiento de la tarea de OdooMRP T0048 - Trazabilidad en Fabricacion.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@clonedagain Thanks for collaborating in the development. There are some requirements that are not expressed in this module, so I'll try to explain to the developer. One of them is the automatic creation of lot number (from the manufacturing order number) if this field is empty. Another is to derive the lot number from its components (this is very common when you have MOs that serves for packaging or labelling product). Raw materials: final product + package. Lot number: lot number of final product + package lot number. This is needed because manufacturing with their policy (have some stock level) can't be done in one step, because packaging depends on the sale (country target of the sale, for example)

@alfredoavanzosc, Lionel lleva razón. Deberías colocar un many2one para poder elegir uno ya existente (por ejemplo, para ampliación de una OF) o crearlo nuevo (porque alguien quiera darle un nº específico). Después, ya será sólo enlazarlo con el stock resultante de la producción.

En los requisitos, también se indica que sólo se concatenarán los nº de serie de los componentes cuando el producto lleve una marca que lo indique. Si no, debe cogerse el nº de orden de fabricación como nº de serie.

**Comment by clonedagain** [comment]
Gracias @pedrobaeza, creo que entiendo.
Discúlpeme de escribir en ingles, yo entiendo lo que vosotros escriben pero no puedo responder en español.

**Comment by alfredoavanzosc** [comment]
Pedro, los requisitos han cambiado totalmente, a petición de Ana. Ahora en la orden de fabricación tendrás la posibilidad de escribir algo en el nuevo campo "Lote de producción manual". Si se pone algo en este nuevo campo, al movimiento del producto a producir, se le creará un lote con el valor de este nuevo campo.
Si el campo "Lote de producción manual" esta vació, entonces se crea un lote al movimiento del producto a producir, con la concatenación de los lotes de todos los productos que se han consumido.
Como ves... los requerimientos han cambiado bastante.

**Comment by anajuaristi** [comment]
Son los mismos... No ha cambiado nada con respecto al texto de la tarea.
Solo que el check en vez de ser "envasado" es ahora "concatenar
componentes".
Nada mas. El resto es igual.

**Comment by pedrobaeza** [comment]
@alfredoavanzosc, procede entonces como te he comentado.

**Comment by anajuaristi** [comment]
Hi @clonedagain @pedrobaeza @alfredoavanzosc 

I think the meaning of the field lot in MO, has not been well understood. 
It can  not be a many2one to lots, simply because the lot in a manufacturing product will be created when manufactured product is created. That is, when production finish or when the production operation (only in odoomrp) finish.

It has no sense creating before the lot, since the order could be cancelled, not started... not made, even be deleted, so we would have an "orphan" object there. 
On the other side, it would be impacting on the way Odoo standar creates the lot / quant, on production stock.move, so... the field is just a text box (required for one of our customers) who wants to "name" created lot in an specific way. 
Creating the lot will write his name, with that field content, just if user writes something and it will work as standard if field is empty.

Wishing my explanation has clarified your concerns, thank you:
Ana

**Comment by alfredoavanzosc** [comment]
Realizada la modificación solicitada por Ana, y subido el módulo.

**Comment by clonedagain** [comment]
@anajuaristi you wrote "we would have an "orphan" object there.", but what harm would it do?
"it would be impacting on the way Odoo standar creates the lot / quant, on production stock.move": would you be kind enough to elaborate please? I'm not yet familiar with the new WMS but that sounds worrying.

**Comment by anajuaristi** [comment]
"we would have an "orphan" object there.", but what harm would it do?
No harm, but just unnecesary confusing element.

"it would be impacting on the way Odoo standar creates the lot / quant, on production stock.move": would you be kind enough to elaborate please? I'm not yet familiar with the new WMS but that sounds worrying.
Don't worry. I mean... IN ANY manufacturing company in the world, lot on manufacturing is created when semielaborated or final product is produced. Not before. Not after. 
Usually, one manufacturing order could produce diferent lot's/serial numbers, most usual is creating a single one. There is no reason, not advantage on creating a lot on MO header breaking the process. Let's do it where and when is necesary, on final product stock.move. That's all. It's not about new Wms, not even about odoo. It's just a  manufacturing standar concept in any tool.

**Comment by clonedagain** [comment]
OK thanks Ana for this sharp opinion. I'm not convinced for now, I think 
it's deeper than this but I'll need to think about it. I'll let you know 
if I can learn something from the disturbance I feel in the Force.

**Comment by anajuaristi** [comment]
@pedrobaeza este también se puede mergear... 
Cuando puedas

**Comment by pedrobaeza** [comment]
Lionel dice que tiene que pensarlo, y yo estoy de acuerdo. Sabes que lo que no me convence, no me convence, y sigo pensando que sería mejor un many2one, aunque tú digas que genera basura si se cancela. Cuánta basura generas por otro lado...

**Comment by anajuaristi** [comment]
Pues si al final meteis un many2one, tendreis que tocar el tema de la asignación automática cuando se crea el movimiento de stock y demás... 
como veas, pero veo un poco absurdo tener parado el tema por algo filosófico. Sea como sea acabémoslo y si es necesario pues queda con el cliente que lo que pidió fue simplemente un sitio donde poner un nombre que él quisiera, sin más y le convenceis @clonedagain y @pedrobaeza de que es mejor crear el lote al principio. 
Pero es necesario acabarlo ya.

**Comment by anajuaristi** [comment]
Por cierto.. comentar que si creamos el lote antes de lanzar la orden, posteriormente tendreis que adecuar los campos de garantía y caducidad, cuando finalice la orden y además, tendreis que controlar que el lote no se pueda seleccionar en ningún sitio, ni en fabricación, ni en salida ni nada. Me direis que la asignación automática no lo cogerá porque no tiene stock, pero manualmente se podrá seleccionar si existe. 
Causa muchos efectos laterales el crear el lote sin haberlo fabricado. Insisto... como querais. Me retiro del tema. Pero por mi parte, voto fervientemente por crear el lote cuando realmente hay que crearlo.

**Comment by pedrobaeza** [comment]
Eso se hace igual, Ana, ya que un proceso (creación o vinculación del lote) no interfiere con esa asignación (se hace en un método aparte a posteriori), e igualmente pasa con lo de elegir el lote (en el momento en que se cree, se podrá elegir en otros sitios, da igual que sea 2 segundos antes que después), pero bueno, para que no sigas dando la tabarra, lo dejaremos así de momento.

**Comment by clonedagain** [comment]
@anajuaristi @pedrobaeza fair enough, by all means do move on and we can always improve it later. Our users have this requirement too so I'll check with them which way they prefer, and hopefully I'll have a constructive first hand experience to share by the time you propose this for OCA.

**Comment by anajuaristi** [comment]
@clonedagain thank you!! I agree with you. Module has been merged by now so it can be tested/improved if needed.

**Pull request merged**
