### PR TITLE
[FIX] Check for track_all

### PR DESCRIPTION
**Pull request by StefanRijnhart**
cf. https://github.com/odoo/odoo/pull/4223/files

### CODE REVIEW

**Comment by oihane** [comment]
@pedrobaeza :+1:

**Comment by oihane** [comment]
After talking with @pedrobaeza I made a little research. If you check _track_all_ the other checks disappear, you could think that they are also checked, but the point is that if they weren't they are not now (I checked the database), so I think the approach made by @StefanRijnhart is the good one.
Of course the last word is from @pedrobaeza :wink:

**Comment by StefanRijnhart** [comment]
Thanks for the response! It is indeed this bad usability that track_production becomes invisible when track_all is active, and it is not synchronized in the background. As you can thus have track_all without track_production, you have to check both.

**Comment by pedrobaeza** [comment]
As you have confirmed the usability issue, both comparisons are needed, so :+1: for this PR.

Thank you very much for reporting.

@oihane, please make a raw search over the repository to see where this check is used to see if we have similar issues.

**Comment by oihane** [comment]
@pedrobaeza search done, it seems that the only one without _track_all_ is the one @StefanRijnhart has found.

**Comment by pedrobaeza** [comment]
OK, thanks.

**Comment by StefanRijnhart** [comment]
Yes I had already checked as well ;-)

**Pull request merged**
