### PR TITLE
[MOD] mrp_bom_by_percentage: update code

### PR DESCRIPTION
**Pull request by esthermm**

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
:-1: to add dependencies on a current version, and more if this doesn't add too much value. Add a new glue module.

**Review by alfredoavanzosc — COMMENTED** [review]
:+1:

**Comment by esthermm** [comment]
@pedrobaeza just update code :smile:

**Review by pedrobaeza — APPROVED** [review]

**Comment by esthermm** [comment]
@odoomrp/developers take a look pls

**Review by oihane — APPROVED** [review]

**Pull request merged**
