### PR TITLE
Add attrs and correct description on po creation

### PR DESCRIPTION
**Pull request by levkar**
This improves purchase order line creation by adding attributes and description

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the PR.

:+1: when Travis goes green.

P.S.: FYI, we are updating these modules for having an abstract class with the common stuff in one place. You can check product_variants_no_automatic_creation and stock_product_variants that are already with this new architecture, and next are sale_product_variants and purchase_product_variants.

**Comment by pedrobaeza** [comment]
Please take care of the flake8 error: 

```
purchase_product_variants/models/procurement_order.py:25:33: E128 continuation line under-indented for visual indent
```

**Comment by oihane** [comment]
And this pylint error:

```
purchase_product_variants/__openerp__.py:19: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
```

**Comment by levkar** [comment]
Pedro, It's great to see improvement on these modules. I hope we can easily upgrade existing deployments.

I have some more improvements on these modules (sale_product_variants & purchase_product_variants) like sale and purchase description (description_sale, description_purchase) inclusion on description.

Do you think it's better to merge them now or after the update?

PS: runbot failed for some other reason this time :)

**Comment by pedrobaeza** [comment]
AFAIK, the description_sale is already there in https://github.com/odoomrp/odoomrp-wip/blob/6ecb5e59462fd5348753fc69dbd6d57270a48e75/sale_product_variants/models/sale_order.py#L141-L142, so I don't know if you refer to other thing.

You can track the progress of this task in the PR https://github.com/odoomrp/odoomrp-wip/pull/1196, so maybe you can wait until we finish it.

**Comment by levkar** [comment]
yes it looks like I committed the description fix :)

https://github.com/odoomrp/odoomrp-wip/commit/60db16364f64ea0e7aca13fa92f0c3f122a7e487

It has been a while since I haven't been looking into it. There are fixes for multi language translations and such. I was very busy to commit these fixes. I will follow the PR and send it later. Better we avoid double work.

**Pull request merged**
