### PR TITLE
[IMP] quality_control_sample: Added tests + improved flow + demo

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Prueba en https://github.com/odoomrp/odoomrp-wip/pull/1060 si sigue ocurriendo

**Comment by anajuaristi** [comment]
Functionally tested in runbot, it works properly :+1: (RTM)

**Comment by oihane** [comment]
El test del quality_control_sample esta dando error (a parte del de quality_control_mrp por el puñetero delivery)

```
2015-11-14 10:43:13,623 23081 ERROR openerp_test openerp.addons.quality_control_samples.tests.test_quality_control_sample:
`     self.assertEqual(len(inspection.inspection_lines), 6)
2015-11-14 10:43:13,624 23081 ERROR openerp_test openerp.addons.quality_control_samples.tests.test_quality_control_sample:
` AssertionError: 2 != 6
```

**Comment by pedrobaeza** [comment]
This is because https://github.com/OCA/manufacture/pull/48 was not merged. I merge now.

**Pull request merged**
